### ISSUE TITLE
How to keep components updated?

### ISSUE THREAD

**Issue by micky2be** [sealninja/react-i18nify#13] opened 2016-11-10 09:42 UTC
In the readme one can read:
> If you choose to use I18n.l or I18n.t then it up to you to handle state change.

But how? Does `react-i18nify` provide an API to know when local value has been changed?
This part is really unclear about the way to update those components.

Would it help using the redux version, would it update for me?
If yes, how to use it?

**Comment by andersonrocha0** [comment] 2016-11-18 17:05
@micky2be Did you know how to do it? I need update my placeholders too when the locale is changed.

**Comment by micky2be** [comment] 2016-11-21 05:37
No, I'm still looking for the right solution.

**Comment by andersonrocha0** [comment] 2016-11-21 08:11
Tks.

Em 21 de nov de 2016 03:37, "Micky Brunetti" <notifications@github.com>
escreveu:

**Comment by gerbenmeyer** [comment] 2016-11-22 11:53
I would be happy to know if anyone of you found a clever way of solving this. The only way I can think of now is to keep a list of components which needs to be updated when the locale changes, and forceUpdate them when this happens, similarly as is done in https://github.com/zoover/react-i18nify/blob/master/src/lib/Base.jsx.

**Comment by Freezystem** [comment] 2017-02-06 09:51
If you take a closer look at other react based i18n libraries ([react-intl](https://github.com/yahoo/react-intl), [react-i18next](https://github.com/i18next/react-i18next)) you can see that your whole application have to be wrapped with a translation dedicated component that handle the state refresh.   

I'll check on that and try to make it work without the need to keep component references in a dedicated array.

**Comment by Freezystem** [comment] 2017-02-10 11:29
So.. I took a deeper look at `HOC` (Higher Order Component) and IMO it's the proper way to solve this problem.
I made a fiddle to show you what it looks like. You can see the whole working code [HERE](https://jsfiddle.net/freezystem/hpsmhz41/).

The problem is that it would takes an entire refacto of the library to correctly wrap and export all components plus it will introduce some breaking changes:
 - `I18n` and its methods become the `HOC` and will not be an exported object anymore.
 - Add a new `<I18nProvider/>` component to wrap the application. 
 - Remove `<Base/>` component: no longer needed as `HOC` will now handle the refresh.
 - Refactor `<Translate/>` and `<Localize/>` components to be wrapped by `HOC`.

Regards.

**Comment by gerbenmeyer** [comment] 2018-01-31 10:27
Is this still an issue? Otherwise I'll close this for now.

**Comment by Ribesg** [comment] 2018-04-24 10:16
This has never been fixed but you just closed the issue?
Am I missing something? Is there some new undocumented thing fixing this?

**Comment by Ribesg** [comment] 2018-04-26 01:10
You mean that the user of this library should update all components containing non-managed translations (`I18n.t`, `I18n.l`) when the user-implemented way of changing language is used (like a button).

This would require implementing and managing a global list of components... Which this library does _anyway_! That's why users like me who report this issue expected a way to bind into this global list, and there's none. I even tried to make my components implement `Base` but it's not exposed, and it would be bad design anyway.

I guess that this issue is mostly inactive because each user who encountered it quickly switched to a different, heavier library allowing them to do what they want.

**Comment by gerbenmeyer** [comment] 2018-04-26 19:09
Of course it's not an issue users switching to other libraries, not every library has to serve everybody's needs. Having said that, I would be happy to have a solution for this, but so far I haven't seen a proper one. 
One issue is that it's not possible to keep a list of `I18n.t` and `I18n.l` usages, because these functions don't return components, but only strings. That's why we only keep track of `<Translate>` and `<Localize>` components, and update those when needed.
Moverover, I also kind of feel that wrapping the whole application in a `<I18nProvider> and `forceUpdate()` everything is a bit of overkill. 
I was considering a compromise of offering a tiny `<I18n>` component which one could use in the following way:

**Comment by Ribesg** [comment] 2018-04-26 19:26
In my case, I switched to this library from others because they were too complex. That's why I agree that a component wrappibng the whole application is overkill.

The solution of a small component wrapping only what's necessary, taking a single child and rendering this child is the best solution, because it's the simplest.

**Comment by gerbenmeyer** [comment] 2018-04-26 19:52
Cool, we're in agreement :)

I'll add such a component to v2 of this library.

**Comment by gerbenmeyer** [comment] 2019-09-04 14:30
Just released v2 of this library, which has a helper for this!

**Closed by gerbenmeyer** 2019-09-04 14:30 UTC
